name: caching

on:
  workflow_dispatch:

jobs:
  use-axios:
    runs-on: ubuntu-latest
    env:
      NODE_HOME: section_04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          echo "we are here: $(pwd)"
          (cd "$NODE_HOME" && pwd)
          (cd "$NODE_HOME") && pwd
          (cd "$NODE_HOME" && npm ci || npm install)
          find *
      - name: Use Axios
        uses: actions/github-script@v7
        with: 
          script: |
            const axios = require('axios');
            const response = await axios("https://icanhazdadjoke.com", { headers: { Accept: "text/plain" } });
            console.log(response.data);
            
      