name: caching

on:
  workflow_dispatch:

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: section_04
        run: |
          (npm ci || npm install)
          find *
      - name: Use Axios
        working-directory: section_04
        run: |
          node -e '
            const axios = require("axios");
            axios("https://icanhazdadjoke.com", { headers: { Accept: "text/plain" } })
              .then(response => console.log(response.data))
              .catch(error => { console.error(error); process.exit(1); });
          ' | tee -a $GITHUB_STEP_SUMMARY
          