name: conc2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: environment
        required: true

concurrency: cg-2

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice title=start::conc2 start at $(date)"
          sleep 30
          echo "::notice title=finish::conc2 finish at $(date)"


        