name: delete-prereleases

on:
  workflow_dispatch:

jobs:

  delete-pre-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run delete pre-releases script
        run: |
          bash .github/workflows/delete-pre-releases.sh