name: delete-prereleases

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'wet-run'
        required: false
        default: false
        type: boolean

jobs:

  delete-pre-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Run delete pre-releases script
        working-directory: .github/workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event.inputs.wet-run }}" == "true" ]]; then
            bash delete-prereleases.sh --wet-run
          else
            bash delete-prereleases.sh
          fi
