name: delete-prereleases

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force delete pre-releases'
        required: false
        default: false
        type: boolean

jobs:

  delete-pre-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run delete pre-releases script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event.inputs.force }}" == "true" ]]; then
            bash .github/workflows/delete-prereleases.sh --force
          else
            bash .github/workflows/delete-prereleases.sh
          fi