name: delete-prereleases

on:
  workflow_dispatch:

jobs:
  manual-intervention:
    runs-on: ubuntu-latest
    steps:
      - name: Request manual approval
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'Delete Pre-Releases Approval'
          inputs:
            approve: 'Please approve to delete pre-releases.'

      - name: Run delete pre-releases script
        run: |
          chmod +x ./delete--pre-releases.sh
          ./delete--pre-releases.sh -f