name: manual

on: 

  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to run on'
        required: true
        default: 'section_02'
        type: string
      message:
        description: 'String to echo'
        required: true
        default: 'Hello, World!'
        type: string
        
jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          {
            echo "### Workflow Inputs"
            echo "- **message**: ${{ github.event.inputs.message }}"
            echo ""
            echo "### GitHub Context Variables"
            echo "- GITHUB_SHA: ${GITHUB_SHA}"
            echo "- GITHUB_REF: ${GITHUB_REF}"
            echo "- GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "- GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "- GITHUB_ACTION: ${GITHUB_ACTION}"
            echo "- GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "- GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "- GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
            echo "- GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "- GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
            echo "- GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
            echo "- GITHUB_JOB: ${GITHUB_JOB}"
            echo "- GITHUB_API_URL: ${GITHUB_API_URL}"
            echo "- GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
            echo "- GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
            echo "- GITHUB_REPOSITORY_ID: ${GITHUB_REPOSITORY_ID}"
            echo "- GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}"
            echo "- GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
            echo "- GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
            echo "- GITHUB_EVENT_REPOSITORY_ID: ${GITHUB_EVENT_REPOSITORY_ID}"
            echo "- GITHUB_EVENT_REPOSITORY_NAME: ${GITHUB_EVENT_REPOSITORY_NAME}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_ID: ${GITHUB_EVENT_REPOSITORY_OWNER_ID}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_LOGIN: ${GITHUB_EVENT_REPOSITORY_OWNER_LOGIN}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_NODE_ID: ${GITHUB_EVENT_REPOSITORY_OWNER_NODE_ID}"
            echo "- GITHUB_EVENT_REPOSITORY_PRIVATE: ${GITHUB_EVENT_REPOSITORY_PRIVATE}"
            echo "- GITHUB_EVENT_REPOSITORY_HTML_URL: ${GITHUB_EVENT_REPOSITORY_HTML_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_URL: ${GITHUB_EVENT_REPOSITORY_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_ARCHIVE_URL: ${GITHUB_EVENT_REPOSITORY_ARCHIVE_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_FORK: ${GITHUB_EVENT_REPOSITORY_FORK}"
            echo "- GITHUB_EVENT_REPOSITORY_CREATED_AT: ${GITHUB_EVENT_REPOSITORY_CREATED_AT}"
            echo "- GITHUB_EVENT_REPOSITORY_UPDATED_AT: ${GITHUB_EVENT_REPOSITORY_UPDATED_AT}"
            echo "- GITHUB_EVENT_REPOSITORY_PUBLISHED_AT: ${GITHUB_EVENT_REPOSITORY_PUBLISHED_AT}"
            echo "- GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH: ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}"
            echo "- GITHUB_EVENT_REPOSITORY_GIT_URL: ${GITHUB_EVENT_REPOSITORY_GIT_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_SSH_URL: ${GITHUB_EVENT_REPOSITORY_SSH_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_CLONE_URL: ${GITHUB_EVENT_REPOSITORY_CLONE_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_SVN_URL: ${GITHUB_EVENT_REPOSITORY_SVN_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_MIRROR_URL: ${GITHUB_EVENT_REPOSITORY_MIRROR_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_ISSUES: ${GITHUB_EVENT_REPOSITORY_HAS_ISSUES}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_WIKI: ${GITHUB_EVENT_REPOSITORY_HAS_WIKI}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_PAGES: ${GITHUB_EVENT_REPOSITORY_HAS_PAGES}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_DOWNLOADS: ${GITHUB_EVENT_REPOSITORY_HAS_DOWNLOADS}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_DISK_USAGE: ${GITHUB_EVENT_REPOSITORY_HAS_DISK_USAGE}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_PROJECTS: ${GITHUB_EVENT_REPOSITORY_HAS_PROJECTS}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_VIEWS: ${GITHUB_EVENT_REPOSITORY_HAS_VIEWS}"
            echo "- GITHUB_EVENT_REPOSITORY_HAS_RELEASES: ${GITHUB_EVENT_REPOSITORY_HAS_RELEASES}"
            echo "- GITHUB_EVENT_REPOSITORY_LICENSE_KEY: ${GITHUB_EVENT_REPOSITORY_LICENSE_KEY}"
            echo "- GITHUB_EVENT_REPOSITORY_LICENSE_NAME: ${GITHUB_EVENT_REPOSITORY_LICENSE_NAME}"
            echo "- GITHUB_EVENT_REPOSITORY_LICENSE_SPDX_ID: ${GITHUB_EVENT_REPOSITORY_LICENSE_SPDX_ID}"
            echo "- GITHUB_EVENT_REPOSITORY_LICENSE_URL: ${GITHUB_EVENT_REPOSITORY_LICENSE_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_LICENSE_NODE_ID: ${GITHUB_EVENT_REPOSITORY_LICENSE_NODE_ID}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_TYPE: ${GITHUB_EVENT_REPOSITORY_OWNER_TYPE}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_SITE_ADMIN: ${GITHUB_EVENT_REPOSITORY_OWNER_SITE_ADMIN}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_AVATAR_URL: ${GITHUB_EVENT_REPOSITORY_OWNER_AVATAR_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_GRAVATAR_ID: ${GITHUB_EVENT_REPOSITORY_OWNER_GRAVATAR_ID}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_EVENTS_URL: ${GITHUB_EVENT_REPOSITORY_OWNER_EVENTS_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWERS_URL: ${GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWERS_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWING_URL: ${GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWING_URL}"
            echo "- GITHUB_EVENT_REPOSITORY_OWNER_GISTS_URL: ${GITHUB_EVENT_REPOSITORY_OWNER_GISTS_URL}"
          } >> $GITHUB_STEP_SUMMARY

