name: manual

on:
  workflow_dispatch:


jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice title=GITHUB_SHA::GITHUB_SHA is ${GITHUB_SHA}"
          echo "::notice title=GITHUB_REF::GITHUB_REF is ${GITHUB_REF}"
          echo "::notice title=GITHUB_EVENT_NAME::GITHUB_EVENT_NAME is ${GITHUB_EVENT_NAME}"
          echo "::notice title=GITHUB_WORKFLOW::GITHUB_WORKFLOW is ${GITHUB_WORKFLOW}"
          echo "::notice title=GITHUB_ACTION::GITHUB_ACTION is ${GITHUB_ACTION}"
          echo "::notice title=GITHUB_ACTOR::GITHUB_ACTOR is ${GITHUB_ACTOR}"
          echo "::notice title=GITHUB_REPOSITORY::GITHUB_REPOSITORY is ${GITHUB_REPOSITORY}"
          echo "::notice title=GITHUB_EVENT_PATH::GITHUB_EVENT_PATH is ${GITHUB_EVENT_PATH}"
          echo "::notice title=GITHUB_WORKSPACE::GITHUB_WORKSPACE is ${GITHUB_WORKSPACE}"
          echo "::notice title=GITHUB_RUN_ID::GITHUB_RUN_ID is ${GITHUB_RUN_ID}"
          echo "::notice title=GITHUB_RUN_NUMBER::GITHUB_RUN_NUMBER is ${GITHUB_RUN_NUMBER}"
          echo "::notice title=GITHUB_JOB::GITHUB_JOB is ${GITHUB_JOB}"     
          echo "::notice title=GITHUB_API_URL::GITHUB_API_URL is ${GITHUB_API_URL}"
          echo "::notice title=GITHUB_GRAPHQL_URL::GITHUB_GRAPHQL_URL is ${GITHUB_GRAPHQL_URL}"   
          echo "::notice title=GITHUB_SERVER_URL::GITHUB_SERVER_URL is ${GITHUB_SERVER_URL}"
          echo "::notice title=GITHUB_REPOSITORY_ID::GITHUB_REPOSITORY_ID is ${GITHUB_REPOSITORY_ID}"
          echo "::notice title=GITHUB_REF_TYPE::GITHUB_REF_TYPE is ${GITHUB_REF_TYPE}"
          echo "::notice title=GITHUB_HEAD_REF::GITHUB_HEAD_REF is ${GITHUB_HEAD_REF}"
          echo "::notice title=GITHUB_BASE_REF::GITHUB_BASE_REF is ${GITHUB_BASE_REF}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_ID::GITHUB_EVENT_REPOSITORY_ID is ${GITHUB_EVENT_REPOSITORY_ID}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_NAME::GITHUB_EVENT_REPOSITORY_NAME is ${GITHUB_EVENT_REPOSITORY_NAME}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_ID::GITHUB_EVENT_REPOSITORY_OWNER_ID is ${GITHUB_EVENT_REPOSITORY_OWNER_ID}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_LOGIN::GITHUB_EVENT_REPOSITORY_OWNER_LOGIN is ${GITHUB_EVENT_REPOSITORY_OWNER_LOGIN}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_NODE_ID::GITHUB_EVENT_REPOSITORY_OWNER_NODE_ID is ${GITHUB_EVENT_REPOSITORY_OWNER_NODE_ID}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_PRIVATE::GITHUB_EVENT_REPOSITORY_PRIVATE is ${GITHUB_EVENT_REPOSITORY_PRIVATE}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HTML_URL::GITHUB_EVENT_REPOSITORY_HTML_URL is ${GITHUB_EVENT_REPOSITORY_HTML_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_URL::GITHUB_EVENT_REPOSITORY_URL is ${GITHUB_EVENT_REPOSITORY_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_ARCHIVE_URL::GITHUB_EVENT_REPOSITORY_ARCHIVE_URL is ${GITHUB_EVENT_REPOSITORY_ARCHIVE_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_FORK::GITHUB_EVENT_REPOSITORY_FORK is ${GITHUB_EVENT_REPOSITORY_FORK}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_CREATED_AT::GITHUB_EVENT_REPOSITORY_CREATED_AT is ${GITHUB_EVENT_REPOSITORY_CREATED_AT}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_UPDATED_AT::GITHUB_EVENT_REPOSITORY_UPDATED_AT is ${GITHUB_EVENT_REPOSITORY_UPDATED_AT}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_PUBLISHED_AT::GITHUB_EVENT_REPOSITORY_PUBLISHED_AT is ${GITHUB_EVENT_REPOSITORY_PUBLISHED_AT}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH::GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH is ${GITHUB_EVENT_REPOSITORY_DEFAULT_BRANCH}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_GIT_URL::GITHUB_EVENT_REPOSITORY_GIT_URL is ${GITHUB_EVENT_REPOSITORY_GIT_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_SSH_URL::GITHUB_EVENT_REPOSITORY_SSH_URL is ${GITHUB_EVENT_REPOSITORY_SSH_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_CLONE_URL::GITHUB_EVENT_REPOSITORY_CLONE_URL is ${GITHUB_EVENT_REPOSITORY_CLONE_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_SVN_URL::GITHUB_EVENT_REPOSITORY_SVN_URL is ${GITHUB_EVENT_REPOSITORY_SVN_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_MIRROR_URL::GITHUB_EVENT_REPOSITORY_MIRROR_URL is ${GITHUB_EVENT_REPOSITORY_MIRROR_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_ISSUES::GITHUB_EVENT_REPOSITORY_HAS_ISSUES is ${GITHUB_EVENT_REPOSITORY_HAS_ISSUES}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_WIKI::GITHUB_EVENT_REPOSITORY_HAS_WIKI is ${GITHUB_EVENT_REPOSITORY_HAS_WIKI}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_PAGES::GITHUB_EVENT_REPOSITORY_HAS_PAGES is ${GITHUB_EVENT_REPOSITORY_HAS_PAGES}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_DOWNLOADS::GITHUB_EVENT_REPOSITORY_HAS_DOWNLOADS is ${GITHUB_EVENT_REPOSITORY_HAS_DOWNLOADS}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_DISK_USAGE::GITHUB_EVENT_REPOSITORY_HAS_DISK_USAGE is ${GITHUB_EVENT_REPOSITORY_HAS_DISK_USAGE}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_PROJECTS::GITHUB_EVENT_REPOSITORY_HAS_PROJECTS is ${GITHUB_EVENT_REPOSITORY_HAS_PROJECTS}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_VIEWS::GITHUB_EVENT_REPOSITORY_HAS_VIEWS is ${GITHUB_EVENT_REPOSITORY_HAS_VIEWS}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_HAS_RELEASES::GITHUB_EVENT_REPOSITORY_HAS_RELEASES is ${GITHUB_EVENT_REPOSITORY_HAS_RELEASES}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_LICENSE_KEY::GITHUB_EVENT_REPOSITORY_LICENSE_KEY is ${GITHUB_EVENT_REPOSITORY_LICENSE_KEY}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_LICENSE_NAME::GITHUB_EVENT_REPOSITORY_LICENSE_NAME is ${GITHUB_EVENT_REPOSITORY_LICENSE_NAME}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_LICENSE_SPDX_ID::GITHUB_EVENT_REPOSITORY_LICENSE_SPDX_ID is ${GITHUB_EVENT_REPOSITORY_LICENSE_SPDX_ID}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_LICENSE_URL::GITHUB_EVENT_REPOSITORY_LICENSE_URL is ${GITHUB_EVENT_REPOSITORY_LICENSE_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_LICENSE_NODE_ID::GITHUB_EVENT_REPOSITORY_LICENSE_NODE_ID is ${GITHUB_EVENT_REPOSITORY_LICENSE_NODE_ID}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_TYPE::GITHUB_EVENT_REPOSITORY_OWNER_TYPE is ${GITHUB_EVENT_REPOSITORY_OWNER_TYPE}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_SITE_ADMIN::GITHUB_EVENT_REPOSITORY_OWNER_SITE_ADMIN is ${GITHUB_EVENT_REPOSITORY_OWNER_SITE_ADMIN}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_AVATAR_URL::GITHUB_EVENT_REPOSITORY_OWNER_AVATAR_URL is ${GITHUB_EVENT_REPOSITORY_OWNER_AVATAR_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_GRAVATAR_ID::GITHUB_EVENT_REPOSITORY_OWNER_GRAVATAR_ID is ${GITHUB_EVENT_REPOSITORY_OWNER_GRAVATAR_ID}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_EVENTS_URL::GITHUB_EVENT_REPOSITORY_OWNER_EVENTS_URL is ${GITHUB_EVENT_REPOSITORY_OWNER_EVENTS_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWERS_URL::GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWERS_URL is ${GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWERS_URL}"    
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWING_URL::GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWING_URL is ${GITHUB_EVENT_REPOSITORY_OWNER_FOLLOWING_URL}"
          echo "::notice title=GITHUB_EVENT_REPOSITORY_OWNER_GISTS_URL::GITHUB_EVENT_REPOSITORY_OWNER_GISTS_URL is ${GITHUB_EVENT_REPOSITORY_OWNER_GISTS_URL}"


