name: mermaid

on:
  push:
  workflow_dispatch: 

env:
  TARGET: doc/mermaid/README.md

jobs:
  update-mermaid:
    runs-on: ubuntu-latest
    env:
      NODE_HOME: section_02
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24.4.1'

      - name: Install dependencies
        run: cd "$NODE_HOME" && (npm ci || npm install)

      - name: Update Mermaid graph in README.md
        run: cd "$NODE_HOME" && (npm run update-mermaid -- "${{ env.TARGET }}")

      - name: Commit and push changes
        run: |
          set -x
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git diff
          git add "${{ env.TARGET }}"
          if git diff --cached --quiet; then
            echo "No changes to commit" >> $GITHUB_STEP_SUMMARY
          else
            echo "Changes made to the following files:" >> $GITHUB_STEP_SUMMARY
            git diff --cached --name-only | sed 's/^/* /' >> $GITHUB_STEP_SUMMARY
            git commit -m "chore: update Mermaid graph in "${{ env.TARGET }}""
          fi
          git push