name: reusable-workflow

on: 

  workflow_dispatch:

  workflow_call:
    outputs:
      date: 
        description: "the date"
        value: ${{ jobs.generate-output.outputs.date }}


jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date-step.outputs.date }}
    steps:
      - run: |
          echo "date=$(date)" >> $GITHUB_OUTPUT
          sed 's/^/GITHUB_OUTPUT: /' < $GITHUB_OUTPUT  >> $GITHUB_STEP_SUMMARY
        id: date-step
        
  nested-wf-call:
    uses: allenhub-net/TCGAaWGuide-a/.github/workflows/reusable.yaml@f82eab47a57d58b31b4a75eb27e42e4c4001ae43 # v2.0.1
    with: 
      name: "Babar"
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

