name: checkout
on:
  - push
  - workflow_dispatch 

jobs: 

  checkout-without-action:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -la

      - name: checkout repo
        run: |
          git init 
          git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch origin
          git checkout main

      - name: list files after
        run: ls -la 


  checkout-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -la

      - name: checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: list files after
        run: ls -la 

