name: big-and-sensitive

on: 
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Decrypt files
        env: 
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          gpg --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output secret.json section_03/secret.json.gpg

      - name: view 
        run: |
          cat secret.json

          