name: big-and-sensitive

on: 
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Decrypt files
        env: 
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          gpg --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output secret.json section_03/secret.json.gpg

      - name: view 
        run: |
          cat secret.json

          