name: big-and-sensitive

on: 
  workflow_dispatch:

jobs:
  decrypt:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Decrypt files
        env: 
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          gpg --batch --yes --decrypt --passphrase="${PASSPHRASE}" --output secret.json section_03/secret.json.gpg

      - name: view 
        run: |
          cat secret.json

          