name: pr-comment

on: 
  pull_request_target:
    types: [opened, edited, reopened]
    
  workflow_dispatch:

permissions:
  issues: read

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new PRs
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Thanks, Dawg (${{ github.actor }}), for your pull request!`
            });
