name: matrix

on:
  - workflow_dispatch
  - push

jobs:

  node-matrix:
    #continue-on-error: true
    strategy:
      matrix:
        node-version: 
          - ''
          - 16
        os:
          - ubuntu-latest
          - windows-latest
      max-parallel: 1
      fail-fast: false
    runs-on: $${ matrix.os }}
    steps: 
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with: 
          node-version: ${{ matrix.node-version }}
      - env: 
          NODE_VER: ${{ matrix.node-version }}
        run: |
          echo "NODE_VER: ${NODE_VER}"
          title="Node ${NODE_VER:-default} version on $${ matrix.os }}"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"
        