name: matrix

on:
  - workflow_dispatch
  - push

jobs:
  node-default:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - run: |
          title="runner node version"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"

  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 14
          - 15
          - 16
    steps: 
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with: 
          node-version: ${{ matrix.node-version }}
      - run: |
          title="Node ${{ matrix.node-version }} version"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"

