name: matrix

on:
  - push

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          title="runner node version"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"

      - uses: actions/setup-node@v3
        with: 
          node-version: 13
      - run: |
          title="Node 13 version"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"

          