name: matrix

on:
  - workflow_dispatch
  - push

jobs:

  node-matrix:
    strategy:
      matrix:
        node-version: 
          - ''
          - 20
          - 19
          - 18
          - 15
        os: [ubuntu-latest, macos-latest]
      fail-fast: true
      max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with: 
          node-version: ${{ matrix.node-version }}
      - env: 
          NODE_VER: ${{ matrix.node-version }}
        run: |
          echo "NODE_VER: ${NODE_VER}"
          title="Node ${NODE_VER:-default} version"
          nv=$(node -v)
          echo "::notice title=${title} on ${{ matrix.os }}::${nv}"
          echo "version: ${nv}"