name: dynamic matrix

on:
  workflow_dispatch:
    inputs: 
      os: 
        description: operating system 
        default: "ubuntu-latest,macos-latest"
        type: string
      node-version:
        description: node version"
        default: "18,19,20"
        type: string



jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value 2" >> $GITHUB_OUTPUT
        id: step-2
      - run: |
          echo '${{ steps.step-1.outputs.step-output }}'
          echo '${{ steps.step-2.outputs.step-output }}'
  node-matrix:
    strategy:
      matrix:
        node-version: 
          - ''
          - 15
          - 18
          - 20
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with: 
          node-version: ${{ matrix.node-version }}
      - env: 
          NODE_VER: ${{ matrix.node-version }}
        run: |
          echo "NODE_VER: ${NODE_VER}"
          title="Node ${NODE_VER:-default} version"
          nv=$(node -v)
          echo "::notice title=${title} on ${{ matrix.os }})::${nv}"
          echo "version: ${nv}"
          echo "matrix: ${{ toJson(matrix)}}"
        