name: matrix

on:
  - workflow_dispatch
  - push

jobs:

  node-matrix:
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        node-version: 
          - ''
          - 15
          - 18
          - 20
        os: [ubuntu-latest, macos-latest]
        include: 
          - os: ubuntu-latest
            is-ubuntu: true
          - experimental: false   
          - os: macos-latest
            node-version: 15
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude: 
          - os: macos-latest
            node-version: 19
      fail-fast: true
      max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps: 

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with: 
          node-version: ${{ matrix.node-version }}
      - env: 
          NODE_VER: ${{ matrix.node-version }}
        run: |
          echo "NODE_VER: ${NODE_VER}"
          title="Node ${NODE_VER:-default} version"
          nv=$(node -v)
          echo "::notice title=${title} on ${{ matrix.os }} (u:${{ matrix.is-ubuntu }} e:${{ matrix.experimental }})::${nv}"
          echo "version: ${nv}"
          echo "is-ubuntu: ${{ matrix.is-ubuntu }}"
      - run: echo '${{ toJson(matrix)}}'
        