name: matrix

on:
  - workflow_dispatch
  - push

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          title="runner node version"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with: 
          node-version: 13
      - run: |
          title="Node 13 version"
          nv=$(node -v)
          echo "::notice title=${title}::${nv}"
          echo "version: ${nv}"

