name: semantic-prerelease

on:
  workflow_dispatch:

  # note: this will run twice if README.md is updated
  # push:
  #   branches:
  #     - section--*

  workflow_run:
    workflows: ["github-markdown-toc"]
    types:
      - completed
    branches:
      - section--*

jobs:
  release:
    name: Semantic Pre-Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Print branch info
        run: echo "Running on branch ${{ github.event.workflow_run.head_branch }}"

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Install semantic-release
        run: npm install --no-save semantic-release @semantic-release/git @semantic-release/changelog

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --plugins "@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/github,@semantic-release/git"
        