name: Enforce Semantic Release Commits

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]


  workflow_dispatch:


jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all commits
        run: git fetch --prune --unshallow

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: npm install -g @commitlint/{cli,config-conventional}

      - name: Lint commit messages 1
        run: |
          if [ -z "${{ github.base_ref }}" ]; then
            # Default to main if base_ref is empty (e.g., workflow_dispatch)
            BASE_REF=main
          else
            BASE_REF=${{ github.base_ref }}
          fi
          git log origin/$BASE_REF..HEAD

      - name: Lint commit messages 2
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:%s
          
      - name: Lint commit messages 3
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:%s | npx commitlint          