name: simple-action
on:
  - push

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@b3aa08b37b75eeae77ad9fbeb19614dd08ecac07
        with: 
          who-to-greet: Mona the Octocat
      
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"







      