name: simple-action
on:
  - push

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@ad41a6c27317e688719c813b0d6a25685a9bce54 # v1.1  
        with: 
          who-to-greet: Mona the Octocat
      
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"







      