name: simple-action
on:
  - push

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@62b1d1451538c799d82253b6061f9d0fbf4089f1
        with: 
          who-to-greet: Mona the Octocat
      
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"







      
