name: using-reusable-workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: "who"
        type: string
        default: 'mallen'
        required: true

jobs:
  calling-a-reusable-workflow:
    uses: allenhub-net/TCGAaWGuide-a/.github/workflows/reusable.yaml@1a3e982917dee6c24169ba63e94b75a3f92e4172 # v1.1.0
    with: 
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

