name: using-reusable-workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: "who"
        type: string
        default: 'mallen'
        required: true

jobs:
  calling-a-reusable-workflow:
    uses: allenhub-net/TCGAaWGuide-a/.github/workflows/reusable.yaml@f82eab47a57d58b31b4a75eb27e42e4c4001ae43 # v2.0.1
    with: 
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}


  calling-a-reusable-workflow-in-same-repo:
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit

  using-reusable-workflow-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-workflow-in-same-repo
    steps: 
      - run: |
          echo ${{ needs.calling-a-reusable-workflow-in-same-repo.outputs.date }} | tee -a $GITHUB_STEP_SUMMARY