name: using-reusable-workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: "who"
        type: string
        default: 'mallen'
        required: true

jobs:
  calling-a-reusable-workflow:
    uses: allenhub-net/TCGAaWGuide-a/.github/workflows/reusable.yaml@63387f88ea68918cf091d0b059e29bb2edf53646 # v2.0.0
    with: 
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}


  calling-a-reusable-workflow-in-same-repo:
    uses: ./.github/workflows/reusable-workflow.yml

  using-reusable-workflow-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-workflow-in-same-repo
    steps: 
      - run: |
          echo ${{ needs.calling-a-reusable-workflow-in-same-repo.outputs.date }}