name: using-reusable-workflows

on:
  workflow_dispatch:
    inputs:
      name:
        description: "who"
        type: string
        default: 'mallen'
        required: true

jobs:
  calling-a-reusable-workflow:
    uses: allenhub-net/TCGAaWGuide-a/.github/workflows/reusable.yaml@93649d6febfab2cb0f682550f25a73728a2b6848
    with: 
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

