name: vscode-extensions

on:
  workflow_dispatch:
    inputs:
      update:
        description: 'update source-controlled list of extensions'
        required: false
        default: false
        type: boolean

jobs:

  delete-pre-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install VS Code CLI
        run: |
          wget -O vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
          sudo apt update
          sudo apt install -y ./vscode.deb

      - name: List Installed VSCode Extensions
        working-directory: doc
        run: |
          set -x
          code --list-extensions --show-versions
          code --list-extensions | awk '!/^Extensions/ {print "code --install-extension", $0}'
          awk -v list_content="$(code --list-extensions --show-versions)" '
              BEGIN { in_block=0 }
              /<!-- extension-list -->/ { print; print list_content; in_block=1; next }
              /<!-- tsil-noisnetxe -->/ { in_block=0 }
              !in_block { print }
            ' README.md

