name: workflow-commands
on:
  - push

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Setting and error message
      run: |
        echo "::error::missing semicolon"

    - name: Setting an error message with parameters
      run: |  
        echo "::error title::Error title, file=app.js, line=2, endLine=3,col=5,endCol=7::Missing another semicolon
                