name: workflow-run

on: 

  workflow_run:
    workflows:
      - events
    type:
      - completed

  workflow_dispatch:

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "::notice title=github context::GITHUB_SHA is ${GITHUB_SHA}\nGITHUB_REF is ${GITHUB_REF}"
