name: workflow-commands
on:
  - push

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Setting and error message
      run: |
        echo "::error::missing semicolon"

    - name: Setting an error message with parameters
      run: |  
        echo "::error::Error title,file=app.js,line=2,endLine=3,col=5,endCol=7::Missing another semicolon"
                
    - name: Setting an debug message with parameters
      run: |  
        echo "::debug::debug title,file=app.js,line=2,endLine=3,col=5,endCol=7::Missing another semicolon"
                
    - name: Setting an warning message with parameters
      run: |  
        echo "::warning::warning title,file=app.js,line=2,endLine=3,col=5,endCol=7::Missing another semicolon"
                

    - name: Setting an notice message with parameters
      run: |  
        echo "::notice::notice title,file=app.js,line=2,endLine=3,col=5,endCol=7::Missing another semicolon"
                